spring:
   profiles:
      active: dev
---
spring:
  config:
    activate:
      on-profile: production
  application:
    name: Testing
  datasource:
      url: jdbc:mysql://192.168.100.90/ingestdb
      username: root
      password: 
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: none
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Testing
  datasource:
      url: jdbc:mysql://localhost:3306/ingestdb
      username: root
      password: 
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error
URL:
  FILE_IN: D:\\Transcoder\\MEDIA_IN\\MEDIA_INBOX
  FILE_PRIEVIEW: D:\\Transcoder\\H264_OUT
  DOWNLOAD_HI_RES: D:\\Transcoder\\MEDIA_OUT
  DOWNLOAD_LOW_RES: D:\\Transcoder\\MEDIA_OUT
EXTENSION:
  FILE_DOWNLOAD: .mxf  
---
spring:
  config:
    activate:
      on-profile: testing
  application:
    name: Testing
  datasource:
      url: jdbc:mysql://localhost:3306/ingestdb
      username: root
      password: 
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error
URL:
  FILE_IN: C:\\video
  FILE_PRIEVIEW: C:\\video
  DOWNLOAD_HI_RES: C:\\video
  DOWNLOAD_LOW_RES: C:\\video
EXTENSION:
  FILE_DOWNLOAD: .mp4