spring:
   profiles:
      active: production
---
spring:
  config:
    activate:
      on-profile: production
  application:
    name: Testing
  datasource:
      url: jdbc:mysql://localhost:3306/ingestdb
      username: root
      password: ImNumber4#
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: none
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0
server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: Testing
  datasource:
      url: jdbc:mysql://localhost:3306/ingestdb
      username: root
      password: 
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error
URL:
  FILE_IN: D:\\
  FILE_PRIEVIEW: \\192.168.6.30\\h264_out
  DOWNLOAD_HI_RES: \\192.168.6.30\\media_out
  DOWNLOAD_LOW_RES: D:\\Transcoder\\MEDIA_OUT
EXTENSION:
  FILE_DOWNLOAD: .mxf  
---
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  config:
    activate:
      on-profile: testing
  application:
    name: Testing
  datasource:
      url: jdbc:mysql://localhost:3306/ingestdb
      username: root
      password: 
      driverClassName: com.mysql.cj.jdbc.Driver
  jpa: 
      database: default
      hibernate: 
         dialect: org.hibernate.dialect.MySQL5InnoDBDialect
         ddl-auto: update
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:/templates/
  resources:
    static-locations: classpath:/static/
    cache:
      period: 0
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
server:
  port: 8082
  error:
    whitelabel:
      enabled: false
    path: /error
URL:
  FILE_IN: C:\\video
  FILE_PRIEVIEW: C:\\video
  DOWNLOAD_HI_RES: C:\\video
  DOWNLOAD_LOW_RES: C:\\video
# URL:
#   FILE_IN: \\192.168.6.30\\media_in\\inbox
#   FILE_PRIEVIEW: \\192.168.6.30\\h264_out
#   DOWNLOAD_HI_RES: \\192.168.6.30\\media_out
#   DOWNLOAD_LOW_RES: \\192.168.6.30\\media_out
EXTENSION:
  FILE_DOWNLOAD: .mxf
FTP:
  REMOTE_HOST: 192.168.6.30
  USERNAME: reporter
  PASSWORD: reporter123